---
    apiVersion: v1
    kind: ConfigMap
    metadata:
        name: system-dashboard-cm
    data:
      system-dashboard.json: |
            {
            "annotations": {
            "list": [
                {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
                }
            ]
            },
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "id": 4,
            "links": [],
            "panels": [
            {
                "aliasColors": {},
                "bars": false,
                "dashLength": 10,
                "dashes": false,
                "datasource": null,
                "fill": 1,
                "fillGradient": 0,
                "gridPos": {
                "h": 9,
                "w": 12,
                "x": 0,
                "y": 0
                },
                "hiddenSeries": false,
                "id": 2,
                "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": true,
                "total": false,
                "values": false
                },
                "lines": true,
                "linewidth": 1,
                "nullPointMode": "null",
                "options": {
                "dataLinks": []
                },
                "percentage": false,
                "pluginVersion": "6.5.0",
                "pointradius": 2,
                "points": false,
                "renderer": "flot",
                "seriesOverrides": [],
                "spaceLength": 10,
                "stack": false,
                "steppedLine": false,
                "targets": [
                {
                    "expr": "process_cpu_usage{instance=\"urlmanager-svc:8080\",job=\"url-manager\"}",
                    "instant": false,
                    "intervalFactor": 1,
                    "legendFormat": "{{job}}",
                    "refId": "A"
                }
                ],
                "thresholds": [],
                "timeFrom": null,
                "timeRegions": [],
                "timeShift": null,
                "title": "URL Manager CPU usage",
                "tooltip": {
                "shared": true,
                "sort": 0,
                "value_type": "individual"
                },
                "transparent": true,
                "type": "graph",
                "xaxis": {
                "buckets": null,
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
                },
                "yaxes": [
                {
                    "format": "short",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": true
                },
                {
                    "format": "short",
                    "label": null,
                    "logBase": 1,
                    "max": null,
                    "min": null,
                    "show": true
                }
                ],
                "yaxis": {
                "align": false,
                "alignLevel": null
                }
            }
            ],
            "refresh": "5s",
            "schemaVersion": 21,
            "style": "dark",
            "tags": [],
            "templating": {
            "list": []
            },
            "time": {
            "from": "now-1h",
            "to": "now"
            },
            "timepicker": {},
            "timezone": "",
            "title": "System Dashboard",
            "uid": "Db6-SCjZk",
            "version": 1
            } 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config-cm
data:
    dashboard.yml: |-
      apiVersion: 1
      providers:
      - name: general
        # leave empty for general folder
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards/general

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources-config-cm
data:
  datasources.yml: |-
    # config file version
    apiVersion: 1
    
    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Graphite
        orgId: 1
    
    # list of datasources to insert/update depending
    # what's available in the database
    datasources:
      # <string, required> name of the datasource. Required
    - name: Prometheus
      # <string, required> datasource type. Required
      type: prometheus
      # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> url
      url: http://prometheus-svc:9090
      # <string> Deprecated, use secureJsonData.password
      password:
      # <string> database user, if used
      user:
      # <string> database name, if used
      database:
      # <bool> enable/disable basic auth
      basicAuth:
      # <string> basic auth username
      basicAuthUser:
      # <string> Deprecated, use secureJsonData.basicAuthPassword
      basicAuthPassword:
      # <bool> enable/disable with credentials headers
      withCredentials:
      # <bool> mark as default datasource. Max one per org
      isDefault: true 
      # <map> fields that will be converted to json and stored in jsonData
      jsonData:
      # <string> json object of data that will be encrypted.
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: true
      default: true
      scrapeInterval: 5s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: myapp
        image: grafana/grafana:6.5.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
            - mountPath: /etc/grafana/provisioning/dashboards/general
              name: system-dashboard-cm
            - mountPath: /etc/grafana/provisioning/dashboards/
              name: dashboard-config
            - mountPath: /etc/grafana/provisioning/datasources/
              name: datasources-config
      volumes:
          - name: system-dashboard-cm
            configMap:
              defaultMode: 0777
              name: system-dashboard-cm
          - name: dashboard-config
            configMap:
                defaultMode: 0777
                name: dashboard-config-cm
          - name: datasources-config
            configMap:
                defaultMode: 0777
                name: datasources-config-cm
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030