apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        volumeMounts:
            - name: prometheus-cm
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-cm
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-storage-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data: 
    prometheus.yml: |-
        global:
          scrape_interval: 15s
          evaluation_interval: 15s
          
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
            - targets: ['prometheus-svc:9090']
              
          - job_name: 'url-manager'
            metrics_path: '/actuator/prometheus'
            scrape_interval: 5s
            static_configs:
            - targets: ['urlmanager-svc:8080']

