apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: urlmanager
  namespace: urlapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: urlmanager
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: urlredirect
  namespace: urlapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: urlredirect
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authapp
  namespace: urlapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: authapp
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80