apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: urlapp
  name: urlredirect
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: urlredirect
  template:
    metadata:
      labels:
        app: urlredirect
    spec:
      containers:
      - name: urlredirect
        image: egeyosunkaya/urlredirect:0.1
        resources:
          requests:
            memory: 128Mi
            cpu: 200m
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: /usr/config
              name: urlredirect-app-config
        env:
            - name: SPRING_CONFIG_LOCATION
              value: /usr/config/application.yml
      volumes:
          - name: urlredirect-app-config
            configMap:
                  defaultMode: 420
                  name: urlredirect-app-config

---
apiVersion: v1
kind: Service
metadata:
  namespace: urlapp
  name: urlredirect-svc
spec:
  selector:
    app: urlredirect
  ports:
  - name: http
    port: 80
    targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: urlapp
  name: urlredirect-app-config
data:
  application.yml: |-
    spring:
      jpa:
        database: postgresql
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            generate-ddl: true
      datasource:
        url: jdbc:postgresql://postgresql-svc:5432/url
        username: urlmanager
        password: urlmanager
        initialization-mode: always
    management:
      endpoints:
        web:
          exposure:
            include: prometheus
    jwt:
      secret: cloudproject


